### ISSUE TITLE
orgzly-revived fails to sync local folder 

### ISSUE THREAD

**Issue by ieugen** [orgzly-revived/orgzly-android-revived#133]
I did the following steps
- I have installed orgzly-revived 1.8.14 from f-droid.
- I have added a local folder from my SD-card where I sync org files using syncthing
- I opened org files and viewed the agenda - all worked ok
- When I tried to sync the files back i got an error: "Notebook has no link and one or more remote notebooks with the same name exist"

Related issues:
- https://github.com/orgzly-revived/orgzly-android-revived/issues/104

This is a screen capture of the error:

![WhatsApp Image 2024-01-01 at 14 12 47](https://github.com/orgzly-revived/orgzly-android-revived/assets/1050920/27dbc21c-e29d-4548-b941-b12293305cae)

**Comment by ieugen** [comment]
Related to https://github.com/orgzly/orgzly-android/issues/1023

**Comment by BrianA-MN** [comment]
Have you tried the built-in sync mode of orgzly?  Why are you using syncthing to sync the android's notebook file with the android SD card file?  Or can you please describe where the SD card is mounted?

**Comment by ieugen** [comment]
Hi, @BrianA-MN .

I did try - that is what caused the issues IMO. 
To me is a bit confusing why orgzly needs to sync to a local folder. 

- I use emacs on my computer for org-mode
- I use syncthing to sync my files to other computers, including my mobile phone https://syncthing.net/ 
- On my mobile phone I have orgzly installed
- I have added a repository with the path to my org files on the phone
- Orgzly successfully imported Notebooks from there

I had the above issues when I did not have auto-sync enabled very often.
Now I have enabled them and things are ok (using it for a week or so). 

The issue I believe stems from how orgzly is designed and how I use it. 
Orgzly is design to be the source of truth more or less in regards to notes. 
But in my case the source of truth is outside orgzly, in my org folder that I sync across devices.

It would be nice to have orgzly use the folder on the device directly and not require a sync with it's internal structures. 
If that where the case, this issue would not exist IMO. 

From what I could tell, this issue happened because org files changed and orgzly got confused when it tried to sync between it's internal state and the org folder on SD card that I sync with my devices.

I don't know if it's possible for orgzly to use the SD card directly and have no internal state for file contents.

Here are the config I use (it might help someone): 

![Screenshot_20240118-084606_Orgzly Revived](https://github.com/orgzly-revived/orgzly-android-revived/assets/1050920/a2107e71-f4bd-4dfe-bae6-4d0126d0f3ff)
![Screenshot_20240118-084620_Orgzly Revived](https://github.com/orgzly-revived/orgzly-android-revived/assets/1050920/dcadbc8b-ee9b-4983-9a3a-fd89feec5e0b)
![Screenshot_20240118-084720_Orgzly Revived](https://github.com/orgzly-revived/orgzly-android-revived/assets/1050920/1070df97-6c96-4adb-a426-44756dede3ad)

**Comment by BrianA-MN** [comment]
I notice that you have the org repository (the files for each notebook) under the directory for Syncthing, Is Syncthing also watching that folder and updating it each time the file changes on another device?  If yes then you need all the "auto-sync" settings your have, especially the one for auto-sync on startup, resume, and suspend.  Otherwise syncthing will update the repository files, but orgzly would continue to use the notebook in its program location, without looking at the repository version. 
 This is how org-mode works with Emacs also.  Think of the folder where syncthing has placed the org files on your primary computer, if you open the org file and keep it in the buffer of EMACS but syncthing makes an update to the file from an addition on the mobile, you will be working on the Emacs buffer version which won't show the update from the mobile, and there will be a conflict which Emacs can't resolve because it doesn't recognize it, and will be lost when you save the buffer (save that file).  Same issue but on another platform.  With orgzly it is the same issue. thus changes are made in both versions when a orgzly manual sync is attempted and orgzly doesn't have the ability (yet) to resolve the conflict.  
 It is important to keep in mind which file is open, which is being modified, and how often to save or re-open a file to incorporate updates, whether in orgzly or Emacs org-mode. 

It may be  that you are looking not for file sharing, but file collaboration,  more like LibreOffice, Abiword and some other word processors provide.  That doesn't exist in orgzly and Emacs org-mode at this time.  For reasons explained above you can see that collaboration isn't available in orgzly or org-mode, and wouldn't be solved by a different "syncing" method.  Probably your settings for "auto-sync" are the closest possible, but it also eats up a lot of data transfers from the mobile to other devices.  

I work on org files in both orgzly and Emacs org-mode.  I use git syncing with Emacs from the orgzly repository.  I'm not totally familiar with Syncthing, but I don't believe it provides file collaboration either, rather it offers file sync for what ever file is saved to storage device (be it cloud, disk, or whatever).  Since Emacs org-mode doesn't autosave you will always have a chance for a sync issue with any other device.  

Again, hope this helps.  Cheers,

**Comment by ieugen** [comment]
Hi @BrianA-MN ,

Thanks. It helps. 

> Is Syncthing also watching that folder and updating it each time the file changes on another device 

Yes, this is how syncthing works. 
The protocol is quite simple https://docs.syncthing.net/specs/bep-v1.html#bep-v1 and pretty secure. 

I am not looking for collaboration at this stage. 
I was expecting orgzly to detect file changes / check more often. 
I am ok with the current setup.

I actually downloaded the file and tried to build it and see if I can contribute some things.
It failed to build on my system with some linting error regarding android version I think ? 

I am all set.
