### ISSUE TITLE
Support subfolders for Sync locations

### ISSUE THREAD

**Issue by markokocic** [orgzly-revived/orgzly-android-revived#175]
When I set up some directory as a sync location, only org files that are located directly in that directory are read. Org files in subfolders are not considered at all. This makes it unnecessary cumbersome to handle use case with org files inside a folder hierarchy. Also, linking between those org files / notebooks doesn't work, since Orgzly knows nothing about subfolders.

It would be good if Orgzly supported subfolders inside an sync location.

There is a similar ticket reported at #146 which is Git related. This one is more general.

**Comment by amberin** [comment]
Yeah, see my last comment in #146, but let's keep them separate, since the problems are different. With Git repos, files in subfolders are loaded but then saved to the wrong path. I'm not really sure about the Android storage access framework and subfolders... I hope it's possible, but we'll see.

**Comment by amberin** [comment]
I believe this must be implemented per repo type, so I'm not sure if we should make this issue about the directory repo type (which seems to be the most popular type), or try to keep it general. (I suspect there is nothing wrong in the general code, but rather in the different repo implementations.)

**Comment by markokocic** [comment]
I think there are two parts of the fix. 
- First is making sure Notebook in Orgzly are directory tree aware regarding non-unique names, relative links and so on... This part is general, regardless of the sync type
- Second part is serialisation of such Notebooks and mapping them to different sync types, and there would be a difference between directory, webdav or git

**Comment by amberin** [comment]
Different repo types don't even necessarily use the same storage abstractions. For instance, a directory with a content:// URL does not use the Java.io.File class, whereas git repos do. So the entire "file" or "directory" concepts are different for different repo types.

**Comment by amberin** [comment]
The corresponding issue in the original repo is https://github.com/orgzly/orgzly-android/issues/225. It's apparently one of Orgzly's issues that people "like" the most. 😉 

I've been trawling the original repo's issues to take stock of the thinking so far, looking for clues on what @nevenz might have explored and ruled out. It seems like they saw notebook folder/grouping support in the UI as a goal, or even prerequisite. That is way out of my comfort zone to take a shot at.

My current hunch is that I might be able to contribute to the following:

1. Add support for some kind of .orgzlyexclude or .orgzlyinclude file (both should be possible) in all repo types. This is #224.
2. Maybe: Take a shot at #227, although I have no idea about its potential difficulties.
3. Load files from all subdirectories, with notebook names including the relative path (relative to repo root). This should avoid the most obvious confusion and be usable, if not always pretty. I've looked into it for directory repos, and it doesn't seem too hard. My questions are mostly around how to make the code reusable and testable across repo types.

I think 3) could be a small but worthwhile step forward. It would not entail any UI changes, but updating the documentation would be important, to make users aware of the new "invisible" exclude/include feature of #224.

I believe these additions should probably happen in the order outlined above, since, when we add the last feature, there might be long-time users who risk suddenly loading a big number of org files from subfolders which are currently being ignored. It would then be important that they can easily a) delete multiple unwanted notebooks, and b) add exclude/include rules as necessary.

**Comment by ngm** [comment]
Thanks for considering and implementing the changes in this order!

> long-time users who risk suddenly loading a big number of org files from subfolders which are currently being ignored

I am in this position - I have a folder of org-roam files in a subfolder of the location where the org files exist that orgzly is aware of.  

There are 487 files in there, which it would be a pain to have to delete from the notebooks list.

If I understand correctly, if I set up the .orgzlyignore file from the recent release now, I could avoid this? Is there a way to test that I have set up the ignore file correctly?

**Comment by amberin** [comment]
> If I understand correctly, if I set up the .orgzlyignore file from the recent release now, I could avoid this? Is there a way to test that I have set up the ignore file correctly?

@ngm Exactly. Git has [the git check-ignore command](https://git-scm.com/docs/git-check-ignore), and the idea is that our file should behave the exact same way, so maybe try that out. To test it for real, you need to trigger a sync in Orgzly. But there is no risk of losing anything permanently. Should your ignore rules become too broad, Orgzly will unlink the affected notebook from the repository, but it will not be deleted. You'll need to re-link it to the repo yourself, once the ignore rules have been adjusted.

**Comment by amberin** [comment]
@ngm I suppose the best way to make sure you get the ignore rules right would be to add a second repo containing a minimum of files, and experiment with an ignore file in that folder.

**Comment by ngm** [comment]
@amberin Thanks, adding a .orgzlyignore and testing it with git check ignore seems like a good approach, I'll try that. 

It's not the end of the world if I have to remove them manually, anyway, now we have the new multiple select 🙂

**Comment by deadcombo** [comment]
Having ended up with 460 notebooks after updating, clearing the local database and adding the local repository with .orgzlyignore in place proved quick and effective.

**Comment by fuzunspm** [comment]
Subfolders is the most important feature by far. I wish I have skill to implement the feature but it's very critical. I hope it will be available soon

**Comment by amberin** [comment]
@fuzunspm It's implemented in the latest beta (1.8.27-beta.1), so if you could try that out and report any bugs, it would be great!

I will add a feature toggle and set it to off by default, before releasing 1.8.27.

**Comment by fuzunspm** [comment]
Didn't know about beta. Thank you very much
