### ISSUE TITLE
Ignored files with .orgzlyignore still push updates to the remote but never receive updates back

### ISSUE THREAD

**Issue by stfl** [orgzly-revived/orgzly-android-revived#190]
I am heavily testing the new git repo implementation with my very full org git repo with notes in sub folders and so on..
I am running into several issues which I am trying to debug.

## what works
- Files ignored in `.orgzlyignore` will be ignored when created Notebooks from a git repo.
- If a new file is created on the remote or a file is not ingored anymore, it will appear in Orgzly.

## what does not work
- If a file is added to `.orgzlyignore` it is **not** removed from Orgzly
- Existing Notes in Orgzly, that are, in fact, ignored, will push changes to the remote but never receive edits from the remote.
  This was the cause of https://github.com/orgzly-revived/orgzly-android-revived/issues/132#issuecomment-1986873377 where I had still had my local Notes, but accidentally had them ignored :see_no_evil: 
- Create a file in Orgzly which is ignored, it will still be pushed to the remote (and never get anything back)

**Comment by amberin** [comment]
I think the current behavior of Git repos is partly expected to be weird, because of #146.

But your experiments are very useful as they bring to light some important questions about the `.orgzlyignore` file.

If Orgzly has a notebook linked to a repo file, and a new ignore rule is added which matches that file - what is the least surprising behavior? I am not sure at all. Should the notebook really be silently deleted from Orgzly? Or should the repo link just be removed? (After all, we do support linking different notebooks to different repos. I personally use this heavily, with good results.)

Secondly, what should happen in your last case, when the user creates a new notebook which gets a repo file name matching an ignore rule? I suppose that linking the file to the repo should fail, somehow. This requires logic which currently does not exist.

These questions need to be answered before we can add support for the .orgzlyignore file to all repo types (which has been discussed in #146, and is something I am currently working on as part of #175).
