### ISSUE TITLE
Git: Missing notebooks are only imported from repo upon remote changes

### ISSUE THREAD

**Issue by amberin** [orgzly-revived/orgzly-android-revived#22]
I thought I was clever when I skipped repo walks if the Git repo has not changed since the last sync.

But this causes problems in at least two situations:

1. During the first sync after cloning. Notebooks have not yet been created, but since nothing changes in the Git repo during sync, Orgzly will not walk the repo to discover the notebooks.
2. If the user deletes a notebook locally to get rid of some weird state which she doesn't want to sync. In this situation, Orgzly should re-create the notebook upon next sync, since it is present in the Git repo, but not locally. But this will not happen until HEAD changes in the Git repo.

Without having thought it through, my gut feeling is that these scenarios could probably be handled by adding some simple comparison of the number of files in the Git repo and the number of notebooks linked to the repo. But we probably don't want to go back to walking the repo during every sync.

**Comment by amberin** [comment]
I found an easy fix in the first scenario. The second one is trickier, but also less severe.

**Comment by amberin** [comment]
Since the first scenario was much more serious than the second, I opened #28 as a separate issue for the second scenario.

**Comment by BrianA-MN** [comment]
In the first scenario are both the local and repository files being deleted, or only the local file, i.e. the file showing in the orgzly interface. If I remember correctly there are actually two files on the android device, the working orgzly db-file and the repository file. During a desktop git sync only the repository would be updated, unless the user first had executed a sync to the repository through the orgzly interface. The the "mobile-git-sync" from the desktop won't know the file is deleted and won't delete it from it's own repository. In other words, the user would need to sync to have the repository updated from the working area.  Then during the mobile-git-sync the desktop master branch will get updated, or at least throw a warning of the file not being able to be sync'ed because it isn't found on the android.  

I use mobile-git-sync daily and have not tried this, but let me know if more is needed.
