### ISSUE TITLE
1.8.26 - Wrong content created at the end of file

### ISSUE THREAD

**Issue by Sergey-Makarov** [orgzly-revived/orgzly-android-revived#395]
- [x] I have searched for existing issues that may be the same as or related to mine.

Devices: Samsung Galaxy Fold 4 (Android 14) / Emulator (Android 13)
Orgzly Revived Version: 1.8.28 from FDroid
Sync repository type (directory/Dropbox/WebDAV/Git): directory

Hey guys! Recently, I was constantly finding myself in a situation when the end of the notes file was somewhat broken.
Reproduction steps were not obvious, i.e. it could happen in various circumstances.

But, luckily, I was able to find a way to reliably reproduce the bug.
Here is a 83-sec demo video with all the steps needed. On this emulator, the app had never been launched before and has a fully clean state. No synchronisation software that could anyhow affect the result is running, either.
https://github.com/user-attachments/assets/461f7417-0bb0-4475-87d9-66e5b2d79a43

**Comment by amberin** [comment]
Great work in reproducing in such a clean way. This is so odd. It feels like it could be related to #385.

**Comment by amberin** [comment]
I'll re-open this and pin it, to allow linking to it from the change log. Just in case more people start to notice weird content appearing in their files, resulting from this bug.

To be clear, this was fixed in v1.8.30.

# Have I lost data?

No data has been lost, but you may have gotten bad cut-off data at the end of your notebook files. This would appear in the last note as garbled content, and that note could then of course have been moved around to some other location.

But the issue was that files were being overwritten without being truncated first, so if content had been removed, the file would still have old content left at the end.

**Comment by amberin** [comment]
Closing this, as the fix has been out for almost two months now.
